"""Adiciona a coluna observacoes na tabela instalacao

Revision ID: 541f86058894
Revises: 
Create Date: 2025-09-04 19:19:08.640008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541f86058894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.String(length=300), nullable=True))
        batch_op.alter_column('data_instalacao',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('relatorio_historico', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('data_fim',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_historico', schema=None) as batch_op:
        batch_op.alter_column('data_fim',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('data_inicio',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('instalacao', schema=None) as batch_op:
        batch_op.alter_column('data_instalacao',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
