"""Criação inicial do banco de dados

Revision ID: 675d9b28f573
Revises: 
Create Date: 2025-09-08 22:00:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675d9b28f573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('instalacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_combo', sa.String(length=50), nullable=False),
    sa.Column('descricao_combo', sa.String(length=100), nullable=False),
    sa.Column('valor_original', sa.Float(), nullable=False),
    sa.Column('valor_arredondado', sa.Float(), nullable=False),
    sa.Column('login_cliente', sa.String(length=100), nullable=False),
    sa.Column('data_instalacao', sa.String(length=20), nullable=False),
    sa.Column('porcentagem_comissao', sa.Float(), nullable=False),
    sa.Column('comissao', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.String(length=300), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    # LINHA CORRIGIDA ABAIXO
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_instalacao_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.String(length=20), nullable=False),
    sa.Column('data_fim', sa.String(length=20), nullable=False),
    sa.Column('total_comissoes', sa.Float(), nullable=False),
    sa.Column('num_instalacoes', sa.Integer(), nullable=False),
    sa.Column('data_salva', sa.DateTime(), nullable=True),
    sa.Column('instalacoes_json', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    # LINHA CORRIGIDA ABAIXO
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_relatorio_historico_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorio_historico')
    op.drop_table('instalacao')
    op.drop_table('user')
    # ### end Alembic commands ###