"""Muda colunas de data para string

Revision ID: 6c7975168bf0
Revises: 541f86058894
Create Date: 2025-09-04 19:22:15.503310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7975168bf0'
down_revision = '541f86058894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacao', schema=None) as batch_op:
        batch_op.alter_column('data_instalacao',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('relatorio_historico', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('data_fim',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_historico', schema=None) as batch_op:
        batch_op.alter_column('data_fim',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('data_inicio',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('instalacao', schema=None) as batch_op:
        batch_op.alter_column('data_instalacao',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
